apiVersion: v1 
kind: Service
metadata:
  name: "$Username-$brand-$product-$random-$i"
  labels:
    app: "$Username-$brand-$product-$random-$i"
    client: "$Username-$random-$i"
    user: "$Username"
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: "$Username-$brand-$product-$random-$i"
  - port: 5900
    protocol: TCP
    name: "$Username-$brand-$product-$random-$i"
    # nodePort : 30380
  selector:
    app: "$Username-$brand-$product-$random-$i"
    client: "$Username-$random-$i"
    user: "$Username"
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "$Username-$brand-$product-$random-$i"
  labels:
    app: "$Username-$brand-$product-$random-$i"
    client: "$Username-$random-$i"
    user: "$Username"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
